source: src
default_build: release
assembly:
  name: dockerlib
  package: net.nosial.dockerlib
  version: 1.0.0
dependencies:
  net.nosial.loglib2: nosial/loglib2@github
  com.symfony.yaml: symfony/yaml@packagist
build_configurations:
  -
    name: debug
    output: 'target/debug/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
    definitions:
      NCC_DEBUG: true
  -
    name: release
    output: 'target/release/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
